FROM golang:1.22 AS build

WORKDIR /app
ENV PATH="/go/bin:${PATH}"

COPY go.mod go.sum ./
RUN go mod download

COPY . /app

RUN CGO_ENABLED=1 GOOS=linux go build -o api main.go


FROM alpine

WORKDIR /app

RUN apk update && apk upgrade
RUN apk add --no-cache sqlite

COPY --from=build /app/api ./

EXPOSE 8080

CMD [ "./api", "http" ]